services:
  langfuse-server:
    image: chris/langfuse:v2.5.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SALT=${SALT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - TELEMETRY_ENABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_ALLOWED_ORGANIZATION_CREATORS=${LANGFUSE_ALLOWED_ORGANIZATION_CREATORS}
      - LANGFUSE_EE_LICENSE_KEY=${LANGFUSE_EE_LICENSE_KEY}
      - DELETE_TRACES_SECRET_KEY=${DELETE_TRACES_SECRET_KEY}
      - SMTP_CONNECTION_URL=${SMTP_CONNECTION_URL}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
